export type TWsActions = {
  WS_CONNECTION_START: string;
  WS_CONNECTION_SUCCESS: string;
  WS_CONNECTION_ERROR: string;
  WS_CONNECTION_CLOSED: string;
  WS_CONNECTION_GET_MESSAGE: string;
};

export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =
  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSED: "ws_CONNECTION_CLOSED" =
  "ws_CONNECTION_CLOSED";
export const WS_CONNECTION_GET_MESSAGE: "WS_CONNECTION_GET_MESSAGE" =
  "WS_CONNECTION_GET_MESSAGE";

export const WS_ACTIONS = {
  WS_CONNECTION_START,
  WS_CONNECTION_SUCCESS,
  WS_CONNECTION_ERROR,
  WS_CONNECTION_CLOSED,
  WS_CONNECTION_GET_MESSAGE,
};
