export const WS_CONNECTION_START = "WS_CONNECTION_START"
export const WS_CONNECTION_START_FOR_AUTH = "WS_CONNECTION_START_FOR_AUTH"
export const WS_CONNECTION_SUCCESS = "WS_CONNECTION_SUCCESS"
export const WS_CONNECTION_ERROR = "WS_CONNECTION_ERROR"
export const WS_CONNECTION_CLOSED = "ws_CONNECTION_CLOSED"
export const WS_CONNECTION_GET_MESSAGE = "WS_CONNECTION_GET_MESSAGE"


